name: Continuos Integration

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: |
          pnpm --filter=./packages/tree-sitter-aeria ci:build
          pnpm --filter=./packages/language-server build
          pnpm --filter=./packages/vscode build

      - name: Run tests
        run: pnpm -r test

      - name: Create release PR
        uses: changesets/action@v1
        with:
          publish: ./.github/scripts/publish.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

